# -*- coding: utf-8 -*-
"""Number Guessing Game

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OibwK95bdnSaEXjysx6L_iYJ42gea_B0
"""

import random

def guess_number():
    print("1부터 20까지의 숫자 중 하나를 생각합니다.")
    answer = random.randint(1, 20)
    count = 0
    
    while count < 5:
        guess = int(input("숫자를 입력하세요: "))
        count += 1
        
        if guess < answer:
            print("제가 생각한 숫자보다 작습니다.")
        elif guess > answer:
            print("제가 생각한 숫자보다 큽니다.")
        else:
            print(f"정답입니다! {count}번 만에 맞추셨습니다.")
            break
    
    if count == 5:
        print(f"아쉽지만 기회를 다 사용하셨습니다. 제가 생각한 숫자는 {answer}입니다.")
print()